spring:
  application:
    name: E-commerce
  datasource:
    url: jdbc:mysql://localhost:3306/Mini_Tec?useSSL=false&serverTimezone=UTC
    username: root
    password: mysql24
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


